// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "proyecto1EDD.h"

std::string proyecto1EDD::echo(const std::string& text)
{
    return "Hi, " + text;
}

